# ==========================================================
#  File generated by saed_28nm_digital.tcl script
#  User: pdk_admin
#  Date: 2016-03-02
# ==========================================================


if {!${insert_clk_gating}} {
   set_dont_use PwcV162T125_STD_CELL_7RF/LATSR_E
   set_dont_use PwcV162T125_STD_CELL_7RF/LATSR_H
   set_dont_use PwcV162T125_STD_CELL_7RF/LATSR_K
   set_dont_use PwcV162T125_STD_CELL_7RF/SLATSR_E
   set_dont_use PwcV162T125_STD_CELL_7RF/SLATSR_H
   set_dont_use PwcV162T125_STD_CELL_7RF/SLATSR_K
}




set_dont_use PwcV162T125_STD_CELL_7RF/DELAY4_C
set_dont_use PwcV162T125_STD_CELL_7RF/DELAY4_F
set_dont_use PwcV162T125_STD_CELL_7RF/DELAY4_J
set_dont_use PwcV162T125_STD_CELL_7RF/DELAY6_A
set_dont_use PwcV162T125_STD_CELL_7RF/DELAY6_B
set_dont_use PwcV162T125_STD_CELL_7RF/DELAY6_C
set_dont_use PwcV162T125_STD_CELL_7RF/DELAY6_F
set_dont_use PwcV162T125_STD_CELL_7RF/DELAY6_J
set_dont_use PwcV162T125_STD_CELL_7RF/DELAY6_M


puts "INFO: avoid_digcells.tcl sourced."
