#!/bin/bash

cp ./latex/*.tex ./
pdflatex ./tesis.tex
pdflatex ./tesis.tex
rm *.log
rm *.aux
rm *.tex
rm *.sty
rm *.out
rm *.lot
rm *.lof
rm *.toc
rm *.idx
mv tesis.pdf ./pdf/tesis.pdf

# Open it in okular
open=`ps -fe | grep "okular ./pdf/tesis.pdf" | grep -vc grep`
if [ $open -eq 0 ]; then
   okular ./pdf/tesis.pdf &
fi
